In [2]:
import tensorflow as tf
print(tf.version)
tf.__version__

<module 'tensorflow._api.v2.version' from 'C:\\Users\\nanda gopal\\anaconda3\\envs\\ctensor2\\lib\\site-packages\\tensorflow\\_api\\v2\\version\\__init__.py'>


'2.2.0'

# scalar variables in tensorflow tf.Variable(), Rank = 0

In [23]:
string = tf.Variable("This is a string", tf.string)
number = tf.Variable(34, tf.int16)
floatno = tf.Variable(3544.566, tf.float64)
string, number, floatno

(<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'This is a string'>,
 <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=34>,
 <tf.Variable 'Variable:0' shape=() dtype=float32, numpy=3544.566>)

In [25]:
print(tf.rank(string))
print(tf.rank(number))
print(tf.rank(floatno))

tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(0, shape=(), dtype=int32)


# vector variables in tensorlow tf.Variable, minimum rank = 1

In [16]:
rank1_tensor = tf.Variable(['apple', 'ok', 'hk'], tf.string)
print(tf.rank(rank1_tensor))
rank1_tensor.shape

tf.Tensor(1, shape=(), dtype=int32)


TensorShape([3])

In [17]:
rank2_tensor = tf.Variable([
    ['h', 'jj', 'vj'],
    ['hgv', 'hsbd', 'jhb']
])
print(tf.rank(rank2_tensor))
rank2_tensor.shape

tf.Tensor(2, shape=(), dtype=int32)


TensorShape([2, 3])

In [21]:
rank3_tensor = tf.Variable([
    [
        ['jvaj', 'hc', 'jhc', 'khbc'],
        ['jvaj', 'hqwbc', 'jhjdwhc', 'khbc']
    ],
    [
        ['jvaj', 'hhc', 'jhc', 'wd'],
        ['ash', 'd', 'jwd', 'hjvd']
    ]
])

print(tf.rank(rank3_tensor))
rank3_tensor.shape

tf.Tensor(3, shape=(), dtype=int32)


TensorShape([4, 2, 4])

In [22]:
rank4_tensor = tf.Variable([
    [
        [
            ['jvaj', 'hc', 'jhc', 'khbc'],
            ['jvaj', 'hqwbc', 'jhjdwhc', 'khbc']
        ],
        [
            ['jvaj', 'hc', 'jhc', 'khbc'],
            ['jvaj', 'hqwbc', 'jhjdwhc', 'khbc']
        ]
    ],
    [
        [
            ['jvaj', 'hc', 'jhc', 'khbc'],
            ['jvaj', 'hqwbc', 'jhjdwhc', 'khbc']
        ],
        [
            ['jvaj', 'hc', 'jhc', 'khbc'],
            ['jvaj', 'hqwbc', 'jhjdwhc', 'khbc']
        ]
    ]
])

print(tf.rank(rank4_tensor))
rank4_tensor.shape

tf.Tensor(4, shape=(), dtype=int32)


TensorShape([2, 2, 2, 4])

# Changing Shape

In [4]:
tensor1 = tf.ones([2,2,3])
tensor2 = tf.zeros([3,2,5])
tensor1,tensor2

(<tf.Tensor: shape=(2, 2, 3), dtype=float32, numpy=
 array([[[1., 1., 1.],
         [1., 1., 1.]],
 
        [[1., 1., 1.],
         [1., 1., 1.]]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2, 5), dtype=float32, numpy=
 array([[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],
 
        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],
 
        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]], dtype=float32)>)

In [9]:
tensor3 = tf.reshape(tensor2, [2,3,5])
tensor4 = tf.reshape(tensor1, [3,2,2])
tensor3, tensor4

(<tf.Tensor: shape=(2, 3, 5), dtype=float32, numpy=
 array([[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],
 
        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2, 2), dtype=float32, numpy=
 array([[[1., 1.],
         [1., 1.]],
 
        [[1., 1.],
         [1., 1.]],
 
        [[1., 1.],
         [1., 1.]]], dtype=float32)>)

In [14]:
t1 = tf.ones([1,2,3])
t2 = tf.reshape(t1, [2,3,1])
t3 = tf.reshape(t2, [3, -1])

print(t1)
print(t2)
print(t3)

t1.shape,t2.shape,t3.shape

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


(TensorShape([1, 2, 3]), TensorShape([2, 3, 1]), TensorShape([3, 2]))

# Evaluating tensors

In [21]:
with tf.compat.v1.Session() as sess: #creates a session using a default graph
    #tensor1.eval()  #"tensor" will of obviously be the name of the tensor
    pass

#this should not be used in tensorflow2 because tf2 runs in eager execution mode by default
#this should be used when using tensorflow1 which is not recomended